"""empty message

Revision ID: d11368db971d
Revises: 
Create Date: 2019-06-01 20:11:05.659591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11368db971d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_user')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_auth_user_username'))
    )
    op.create_table('stock_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_exchange')),
    sa.UniqueConstraint('name', name=op.f('uq_stock_exchange_name'))
    )
    op.create_table('stock_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_industry')),
    sa.UniqueConstraint('name', name=op.f('uq_stock_industry_name'))
    )
    op.create_table('stock_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['stock_exchange.id'], name=op.f('fk_stock_company_exchange_id_stock_exchange')),
    sa.ForeignKeyConstraint(['industry_id'], ['stock_industry.id'], name=op.f('fk_stock_company_industry_id_stock_industry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_company')),
    sa.UniqueConstraint('symbol', name=op.f('uq_stock_company_symbol'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_company')
    op.drop_table('stock_industry')
    op.drop_table('stock_exchange')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
